version: "3.5"

services:
  librenote:
    image: hrshadhin/librenote
    container_name: librenote_core
    restart: unless-stopped
    volumes:
      - ${PWD}/config.yml:/app/config.yml
      - ${PWD}/data:/persist # only for sqlite
      # Only for first time db migrations
      - ${PWD}/infrastructure/db/migrations/sqlite:/app/migrations # sqlite | mysql | postgres
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Dhaka
