app:
  env: test
  host:
  port: 8000
  read_timeout: 2s
  write_timeout: 5s
  idle_timeout: 3s
  context_timeout: 2s
  request_body_limit: "5M"
  max_page_size: 50
  default_page_size: 20
  data_path: ./
  registration_open: true

jwt:
  secret_key: "super_secret_key"
  expire_time: 600s

database:
  type: postgres
  host: localhost
  port: 5432
  name: librenote_test
  username: dev
  password: dev
  ssl_mode: disable
  max_open_conn: 3
  max_idle_conn: 1
  max_life_time: 10s
  debug: true
