app:
  port: 8000
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 30
  request_body_limit: "5M"
  max_page_size: 50
  default_page_size: 20

jwt:
  secret_key: "super_secret_key"
  expire_in_seconds: 86400 # 1 day

database:
  host: localhost
  port: 5432
  name: librenote
  username: dev
  password: dev
  ssl_mode: disable
  debug: true
  max_open_conn: 3
  max_idle_conn: 1
  max_life_time: 10s
