name: Build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    strategy:
      matrix:
        go-version: [ '1.17.x', '1.18.x' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Get dependencies
        run: make dl-deps
      - name: Build binary
        run: make build
      - name: Check binary
        run: make version
